language: node_js
node_js:
  - "12"
  - "11"
  - "10"
  - "9"
  - "8"
  - "7"
  - "6"
  - "6.0"
  - "5"
  - "4"

install:
  - npm install
  - npm run build

script:
  - mocha

before_install:
  - if [ "$TRAVIS_NODE_VERSION" = "4" ]; then nvm install 6; fi
  - if [ "$TRAVIS_NODE_VERSION" = "5" ]; then nvm install 6; fi

before_script:
  - nvm use $TRAVIS_NODE_VERSION
